# Generated by Django 5.0.4 on 2024-04-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st', models.CharField(max_length=10)),
                ('date_time', models.DateTimeField()),
                ('vis', models.IntegerField(default=0)),
                ('t_cld', models.IntegerField(default=0)),
                ('dd', models.IntegerField(default=0)),
                ('fff', models.IntegerField(default=0)),
                ('temp', models.FloatField(default=0)),
                ('dp', models.FloatField(default=0)),
                ('vp', models.FloatField(default=0)),
                ('rh', models.IntegerField(default=0)),
                ('msl', models.FloatField(default=0)),
                ('qnh', models.FloatField(default=0)),
                ('w', models.IntegerField(default=0)),
                ('ww', models.IntegerField(default=0)),
                ('t_lcld', models.IntegerField(default=0)),
                ('cld', models.IntegerField(default=0)),
                ('low', models.IntegerField(default=0)),
                ('mid', models.IntegerField(default=0)),
                ('high', models.IntegerField(default=0)),
                ('high2', models.IntegerField(default=0)),
                ('maxx', models.FloatField(default=0)),
                ('minn', models.FloatField(default=0)),
                ('rr', models.FloatField(default=0)),
                ('rr_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
