# Generated by Django 5.0.4 on 2024-04-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_remove_report_date_time_report_date_report_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='rr_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='st',
            field=models.CharField(max_length=10, verbose_name='st'),
        ),
    ]
