# Generated by Django 5.0.4 on 2024-04-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_alter_report_vp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['date', 'time']},
        ),
        migrations.AddField(
            model_name='report',
            name='archive',
            field=models.BooleanField(default=False),
        ),
    ]
