# Generated by Django 5.0.4 on 2024-04-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_alter_report_options_report_archive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='vp',
            field=models.FloatField(default=0),
        ),
    ]
