# Generated by Django 5.0.4 on 2024-10-14 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_alter_report_vp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='st',
            field=models.CharField(default='TLPC', max_length=10, verbose_name='st'),
        ),
        migrations.AlterField(
            model_name='report',
            name='time',
            field=models.TimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
