# Generated by Django 5.2.7 on 2025-11-03 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_alter_report_date_alter_report_st_alter_report_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-date', '-time']},
        ),
    ]
