# Generated by Django 5.2.7 on 2025-11-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_alter_report_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='rr_time',
            field=models.TimeField(blank=True, default='16:00', null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='time',
            field=models.TimeField(blank=True, default='16:00', null=True),
        ),
    ]
