# Generated by Django 5.2.7 on 2025-11-03 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_alter_report_rr_time_alter_report_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='vp',
        ),
        migrations.AlterField(
            model_name='report',
            name='rr_time',
            field=models.TimeField(blank=True, help_text='hh:mm', null=True),
        ),
    ]
