# Generated by Django 5.2.7 on 2025-11-03 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_remove_report_vp_alter_report_rr_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='rr_time',
            field=models.TimeField(blank=True, default='--:--', help_text='hh:mm', null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='time',
            field=models.TimeField(blank=True, default='hh:mm', help_text='hh:mm', null=True),
        ),
    ]
