# Generated by Django 5.2.7 on 2025-11-03 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_alter_report_rr_time_alter_report_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='rr_time',
            field=models.TimeField(blank=True, default='00:00', help_text='hh:mm', null=True),
        ),
    ]
